### ISSUE TITLE
[BUG]Due to numpy 1.26.4 not supporting Python 3.13, the installation of crewai failed.

### ISSUE THREAD

**Issue by Jontyshaw** [crewAIInc/crewAI#1434] opened 2024-10-12 04:40 UTC
### Description

Due to numpy 1.26.4 not supporting Python 3.13, the installation of crewai failed.

### Steps to Reproduce

1. upgrade python to 3.13
2. install pipx
3. install crewai by pipx

### Expected behavior

Successfully installed crewai

### Screenshots/Code snippets

Fatal error from pip prevented installation. Full pip output in file:
    C:\Users\jonty\pipx\logs\cmd_2024-10-12_12.31.25_pip_errors.log

pip seemed to fail to build package:
    numpy<2.0.0,>=1.26.0

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    ..\meson.build:1:0: ERROR: Unknown compiler(s): [['icl'], ['cl'], ['cc'], ['gcc'], ['clang'], ['clang-cl'], ['pgcc']]
    error: metadata-generation-failed

Error installing crewai.

### Operating System

Windows 11

### Python Version

3.13

### crewAI Version

0.70.1

### crewAI Tools Version

0.70.1

### Virtual Environment

Poetry

### Evidence

λ pipx install crewai
Fatal error from pip prevented installation. Full pip output in file:
    C:\Users\jonty\pipx\logs\cmd_2024-10-12_12.31.25_pip_errors.log

pip seemed to fail to build package:
    numpy<2.0.0,>=1.26.0

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    ..\meson.build:1:0: ERROR: Unknown compiler(s): [['icl'], ['cl'], ['cc'], ['gcc'], ['clang'], ['clang-cl'], ['pgcc']]
    error: metadata-generation-failed

Error installing crewai.

### Possible Solution

numpy upgrade to 2.1.2

### Additional context

none

**Comment by theCyberTech** [comment] 2024-10-13 09:31
Have tried to update Numpy?

Aslo I would recommend installing crewai via our supported methods - https://docs.crewai.com/installation

Closing as this is not a bug

**Closed by theCyberTech** 2024-10-13 09:31 UTC
Labels: bug
