### ISSUE TITLE
Tool callbacks

### ISSUE THREAD

**Issue by BespalovSergey** [crewAIInc/crewAI#747] opened 2024-06-10 09:01 UTC
Hello, we use callback processing to monitor the operation of tools, tell why you use the private [_run](https://github.com/joaomdmoura/crewAI/blob/main/src/crewai/tools/tool_usage.py#L142) method when calling tools, as a result, tool callbacks are not called. It is quite important to monitor and process the operation of tools with callbacks.

**Comment by theCyberTech** [comment] 2024-06-10 09:58
Private functions / methods in Python are not enforced, meaning you can still call them, call back functions do work in crewAI, feel free to drop you crewAI code here's

**Comment by whimo** [comment] 2024-06-11 08:09
BaseTool class in Langchain has a public [`run`](https://github.com/langchain-ai/langchain/blob/27b9ea14a51398e8ff2a4972026178778f85134b/libs/core/langchain_core/tools.py#L355) method, which is the way a tool should be called. Besides calling `self._run`, it also takes care of things such as error handling, and more importantly, fires callbacks on tool start and end.

We use callbacks for monitoring and debugging agents, but currently tool calls are not logged because of callbacks not being called. What do you think about either using BaseTool's public methods or firing the events inside CrewAi code if the former is not possible for some reason?

**Comment by theCyberTech** [comment] 2024-06-11 08:42
I understand but I don't think there is a functional difference when defining run or _run, correct me if I'm wrong

**Comment by whimo** [comment] 2024-06-11 09:31
Not sure what you mean by that. The difference is in the auxiliary stuff that happens inside `run` before and after it executes `_run`, and it's quite important for our use cases. You can refer to the Langchain code: https://github.com/langchain-ai/langchain/blob/27b9ea14a51398e8ff2a4972026178778f85134b/libs/core/langchain_core/tools.py#L355

**Comment by whimo** [comment] 2024-08-17 12:14
Removing the label because the issue is still present.

**Comment by raviraval79** [comment] 2024-08-24 12:21
Thanks. Eagerly waiting for a fix for this. We need to show tool output to custom UI using on_tool_start, on_tool_error, on_tool_end callbacks

**Comment by whimo** [comment] 2024-09-25 11:42
Bumping this because the issue is still present.

**Closed** 2024-10-31 12:17 UTC
Labels: bug, no-issue-activity
