### ISSUE TITLE
Connection Timeout Error with telemetry.crewai.com

### ISSUE THREAD

**Issue by leeeex** [crewAIInc/crewAI#254] opened 2024-02-18 03:20 UTC
Hello ,
I hope this message finds you well. I am reaching out to report an issue that I encountered while using your project.
Description: I encountered a ConnectTimeout error when attempting to connect to telemetry.crewai.com on port 4318. The error message is as follows:

`requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='telemetry.crewai.com', port=4318): Max retries exceeded with url: /v1/traces (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f34caf38280>, 'Connection to telemetry.crewai.com timed out. (connect timeout=10)')`

**Comment by Mirgiacomo** [comment] 2024-02-20 09:41
Follow

**Comment by ansunsujoe** [comment] 2024-02-21 14:38
Related, but I am not able to run CrewAI due to the fact that it hits telemetry.crewai.com which I can't access through my company's proxy. It would be nice if the user could choose to optionally disable telemetry.

**Comment by lm150** [comment] 2024-02-23 00:24
Please fix this. I'm in the same situation as telemetry.crewai.com is blocked for my company as well.

**Comment by slaughters85j** [comment] 2024-02-27 21:03
I cant even hit it my my local environment with telnet.

```
% telnet telemetry.crewai.com 4318
Trying 10.0.0.1...
telnet: connect to address 10.0.0.1: Connection refused
Trying fd6e:6c73:b178:1::1...
telnet: connect to address fd6e:6c73:b178:1::1: Connection refused
telnet: Unable to connect to remote host
```
I also get this about a hundred times during runtime:

```
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='telemetry.crewai.com', port=4318): Max retries exceeded with url: /v1/traces (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f34caf38280>, 'Connection to telemetry.crewai.com timed out. (connect timeout=10)')
```

**Comment by eleqtrizit** [comment] 2024-02-28 17:01
I want to add to this.

**Comment by heyfixit** [comment] 2024-03-01 11:46
it's not pretty, but a tiny bit of monkey patching might get ya there.  Mind the typo on `crewai.telemtry` at the moment. Have a PR to fix that one: https://github.com/joaomdmoura/crewAI/pull/295

```python
from crewai.telemtry import Telemetry

def noop(*args, **kwargs):
    # with open("./logfile.txt", "a") as f:
    #     f.write("Telemetry method called and noop'd\n")
    pass


for attr in dir(Telemetry):
    if callable(getattr(Telemetry, attr)) and not attr.startswith("__"):
        setattr(Telemetry, attr, noop)
```

**Comment by psikosen** [comment] 2024-03-12 18:35
Bump, still is happening on my side, has a fix been pushed to pip ?

**Comment by vipulnath** [comment] 2024-03-13 05:53
I am also facing the same issue even after this.

**Comment by chrissonntag** [comment] 2024-03-19 07:21
Issue #241 has been closed without any comments. We can assume at this point that there is no interest what so ever to implement a flag to turn of the telemetry calls.

**Comment by psikosen** [comment] 2024-03-19 18:22
Yup np, I notice the issue doesn't happen while using Ollama, only while using lmstudio. So it's fine to close.

**Comment by eleqtrizit** [comment] 2024-03-19 18:27
It's not fine to close.  It happens when the telemetry url is being blocked by a firewall.  What you're using has nothing to do with the whether it is OK or not.

**Comment by pudimKBM** [comment] 2024-03-26 14:41
Hey i have a fix for this you can just disable the telemetry calls on the tool usage class and in the crew class 

Like below 
C:/User/.../your-env/site-packages/crewai/crew.py
C:/User/.../your-env/site-packages/crewai/tools/tool_usage.py


You can comment all the telemetry related stuff and should work fine again

**Comment by mabry1985** [comment] 2024-03-30 19:58
bumped, this is an issue still and needs to be resolved. Add an opt out completely option.

**Comment by mabry1985** [comment] 2024-03-30 19:59
I will just roll back to before this was added otherwise

**Comment by gardner** [comment] 2024-03-30 22:33
I just published a pypi package from my opt-out branch: https://pypi.org/project/crewai-clean/

**Comment by alexjst** [comment] 2024-05-14 06:03
I just hit the same problem. I disabled telemetry with one line change to the file "<python_lib_dir>/site-packages/crewai/telemetry/telemetry.py" below:

- self.ready = True
+ self.ready = False

**Comment by Yamijalaa** [comment] 2024-05-16 09:36
I faced the same issue as above. Please help me in resolving this:

requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='telemetry.crewai.com', port=4318): Max retries exceeded with url: /v1/traces (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002311B65F310>, 'Connection to telemetry.crewai.com timed out. (connect timeout=10)'))

**Comment by gardner** [comment] 2024-05-16 11:58
@Yamijalaa 

Set the env var OTEL_SDK_DISABLED=true


```python
import os
from crewai import Agent, Task, Crew, Process
from crewai_tools import SerperDevTool

os.environ["OTEL_SDK_DISABLED"] = "true"
```

**Comment by johnisanerd** [comment] 2024-05-23 01:51
@gardner , I did this as well, just slightly differently:

`OTEL_SDK_DISABLED = "true"`

I get the following message over and over, but the failures were making the output completely unreadable.  

`2024-05-22 21:49:28,225 - 8099684480 - __init__.py-__init__:1198 - WARNING: SDK is disabled.`

**Comment by gardner** [comment] 2024-05-25 19:49
@johnisanerd that warning looks like it come from the Open Telemetry Python SDK [here](https://github.com/open-telemetry/opentelemetry-python/blob/187048a35ee93194a70a45720fa68b78d57b6a97/opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py#L1218).

If you add this to your `/etc/hosts` file:

```
127.0.0.1	telemetry.crewai.com
```

You will not see connection errors.

To test if `OTEL_SDK_DISABLED` has an effect:

If you then run without `OTEL_SDK_DISABLED` being set, you will see the connection errors. This indicates the underlying OpenTelemetry SDK is succesfully disabled when setting `OTEL_SDK_DISABLED = "true"`

**Comment by AJNOURI** [comment] 2024-06-19 12:05
I solved the issue by faking the response from the telemetry url:

.../lib/python3.11/site-packages/opentelemetry/exporter/otlp/proto/http/trace_exporter/__init__.py

```python 
from requests.models import Response
...

    def _export(self, serialized_data: bytes):
        data = serialized_data
        if self._compression == Compression.Gzip:
            gzip_data = BytesIO()
            with gzip.GzipFile(fileobj=gzip_data, mode="w") as gzip_stream:
                gzip_stream.write(serialized_data)
            data = gzip_data.getvalue()
        elif self._compression == Compression.Deflate:
            data = zlib.compress(serialized_data)

        # return self._session.post(
        #     url=self._endpoint,
        #     data=data,
        #     verify=self._certificate_file,
        #     timeout=self._timeout,
        # )
        # Create a fake response object
        fake_response = Response()
        fake_response.status_code = 200  # Set status code to 200 OK
        fake_response._content = b'{"status": "ok"}'  # Optional: fake response content

        return fake_response  
       ``` 
       For now it works like a charm

**Comment by beeapu** [comment] 2024-06-26 11:37
I am still facing this issue but with my personal project.
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ ... \crewai_env\Lib\site-packages\requests\adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='telemetry.crewai.com', port=4319): Max retries exceeded with url: /v1/traces (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001C2A5AD4170>, 'Connection to telemetry.crewai.com timed out. (connect timeout=30)'))

 but when i try to clone this repo: https://github.com/rajib76/multi_agent/blob/main/08_how_to_do_memory_in_crew_01.py its working find i try to compare those but found nothing different. In fact they are running in same environment itself.

**Comment by slimshreydy** [comment] 2024-08-13 22:52
Telemetry went down recently because the crewai.com server itself was experiencing issues, and made it incredibly difficult to develop: https://github.com/crewAIInc/crewAI/issues/1164

**Closed** 2024-09-19 12:17 UTC
Labels: no-issue-activity

**Comment by gardner** [comment] 2024-09-20 10:17
> This issue was closed because it has been stalled for 5 days with no activity.

dissimulado

**Comment by RajeshThakur1** [comment] 2024-09-25 15:53
> @Yamijalaa
> 
> Set the env var OTEL_SDK_DISABLED=true
> 
> ```python
> import os
> from crewai import Agent, Task, Crew, Process
> from crewai_tools import SerperDevTool
> 
> os.environ["OTEL_SDK_DISABLED"] = "true"
> ```

Thank you so much this works for me

**Comment by joaomdmoura** [comment] 2024-09-25 16:01
Hey folks sorry this got automatically close, we did update out docs with instructions to disable it if people want and more details around the data. We did a while ago but I never closed the loop in here: https://docs.crewai.com/telemetry/Telemetry/

**Comment by imarjuna** [comment] 2025-01-23 05:59
Put this in `.env` file; worked for me
```
OTEL_SDK_DISABLED = True
```

**Comment by harsh-gupta10** [comment] 2025-02-18 09:17
I was also facing this issue but it may be mostly due to the firewall blocking access of this [telemetry](https://telemetry.crewai.com/v1/traces) after changing my connection to my personal hotspot from my Ogranasition one it worked.

**Comment by bruce-gene** [comment] 2025-03-16 16:34
> Hey folks sorry this got automatically close, we did update out docs with instructions to disable it if people want and more details around the data. We did a while ago but I never closed the loop in here: https://docs.crewai.com/telemetry/Telemetry/

The link is no longer working. The same problem still exists. It has been so long. Why hasn't the problem been solved yet?

**Comment by kangISU** [comment] 2025-03-24 21:16
> Put this in `.env` file; worked for me
> 
> ```
> OTEL_SDK_DISABLED = True
> ```

works for me
