### ISSUE TITLE
[BUG]CrewAI based LLM takes way long to retrieve contents of a github file

### ISSUE THREAD

**Issue by shivtej-opsverse** [crewAIInc/crewAI#1428] opened 2024-10-11 13:41 UTC
### Description

* I have created an `Github Agent` and a custom tool which reads the given github file and returns the contents.
* I observe that when run this agent and give it a file it takes around 3-5 minutes to retrieve the content. In my opinion this should be quicker.

### Steps to Reproduce

* Create a Github agent 
```
import os

from crewai import Agent
from langchain_openai import AzureChatOpenAI
from app.tools.github_read import github_read


github_agent = Agent(
    role="Github Expert",
    goal="get the details of the github repository and file and either read or write to the given file or raise a pull request. Read the PAT accurately from the question it should be 40 characters long",
    backstory="You're a github expert. You know how to read the github repository and provide the user with the information they need. You can also write and raise a pull request to the github repository.",
    llm=AzureChatOpenAI(
        azure_deployment=os.environ["AZURE_OPENAI_DEPLOYMENT"],
        api_version=os.environ["AZURE_OPENAI_API_VERSION"],
        api_key=os.environ["AZURE_OPENAI_API_KEY"],
        azure_endpoint=os.environ["AZURE_OPENAI_API_ENDPOINT"],
        model="azure/" + os.environ["AZURE_OPENAI_DEPLOYMENT"],
        temperature=0,
        max_tokens=None,
        timeout=None,
        max_retries=2,
    ),
    verbose=True,
    tools=[
        github_read
    ],
)

```
* Create the following tool 
```
from crewai_tools import tool
import requests
import base64
import re
import os


@tool("github_read")
def github_read(url: str, pat: str = None) -> str:
    """Reads the contents of a given GitHub URL, including private repositories if PAT is provided.

    Args:
        url (str): The GitHub URL to read from. It should be in the format https://github.com/owner/repo/blob/branch/path or https://github.com/owner/repo/tree/branch/path
        pat (str, optional): Personal Access Token for accessing private repositories.

    Returns:
        str: The content of the URL if successful, or an error message saying 'Error reading GitHub content'  if not successful
    """

    # Extract owner, repo, and file/directory path from the URL
    match = re.match(
        r"https://github\.com/([^/]+)/([^/]+)(?:/(?:blob|tree)/([^/]+)/(.+))?", url
    )
    if not match:
        return "Error: Invalid GitHub URL format"

    owner, repo, branch, path = match.groups()

    # If path is None, it's likely a repository root
    if path is None:
        path = ""
        branch = "main"  # Assume 'main' as the default branch

    # Construct the GitHub API URL
    api_url = f"https://api.github.com/repos/{owner}/{repo}/contents/{path}"
    if branch:
        api_url += f"?ref={branch}"

    # Construct the headers
    headers = {"Accept": "application/vnd.github.v3+json"}
    if pat:
        headers["Authorization"] = f"token {pat}"

    try:
        response = requests.get(api_url, headers=headers)
        response.raise_for_status()
        data = response.json()

        # Handle directory listing
        if isinstance(data, list):
            return f"Directory listing for {url}:\n" + "\n".join(
                [f"- {item['name']}" for item in data]
            )

        # Handle file content
        content = base64.b64decode(data["content"]).decode("utf-8")
        return content

    except requests.RequestException as e:
        return f"Error reading GitHub content: {str(e)}"

```

* Create a task
```
    primary_task = Task(
        description="give me the exact contents of https://github.com/crewAIInc/crewAI/blob/main/tests/agent_test.py",
        agent=github_agent,
        expected_output="Contents of the github file ",
    )
```
* Run the crew
```
    report_crew = Crew(
        agents=[github_agent],
        tasks=[primary_task],
    )
    result = report_crew.kickoff()
```

* Some Info abput my LLM 
```
AZURE_OPENAI_INSTANCE_NAME=gpt-4o
```

### Expected behavior

* I expect the LLM to return the content quickly(not taking 3 to 5 minutes)

### Screenshots/Code snippets

<img width="1074" alt="Screenshot 2024-10-11 at 7 05 08 PM" src="https://github.com/user-attachments/assets/19bdfb4e-493c-402a-9cce-d71755ee1ffc">

* It takes 2 minutes here but sometimes it takes around 5 minutes

### Operating System

Ubuntu 20.04

### Python Version

3.12

### crewAI Version

0.65.2

### crewAI Tools Version

0.12.1

### Virtual Environment

Venv

### Evidence

Already given above

### Possible Solution

* Please let me know if it should be taking this much time.

### Additional context

None

**Comment by theCyberTech** [comment] 2024-10-13 09:40
Unfortunately we only have best effort support for your own custom tools.

Also ti is not the LLM that connects to GitHub, it is the tool, looking at your tool briefly it looks like it is ok so I woudl imagine the issue lie in either.

1. the size of the repo
2. Networking / Bandwidth issues between yourself and Github.
3. Also take into account of if there are more efficient Python modules for requests

Closing as not a bug

**Closed by theCyberTech** 2024-10-13 09:40 UTC
Labels: bug
